image: continuumio/miniconda3:latest

stages:
  - auth
  - test

before_script:
  - conda create --name slackvk python=3 flask
  - source activate slackvk
  - pip install slacker gunicorn

envs:
  stage: auth
  script:
    - python config.py

slack:
  stage: auth
  script:
    - python auth.py

post:
  stage: test
  script:
    - python main.py &
    - bash tests/post.sh