image: continuumio/miniconda3:latest

stages:
  - auth
  - test

before_script:
  - conda env create --name slackvk
  - source activate slackvk
  - pip install slacker, flask, gunicorn

envs:
  stage: auth
  script:
    - python config.py

slack:
  stage: auth
  script:
    - python auth.py

post:
  stage: test
  before_script:
    - python main.py
  script:
    - bash tests/post.sh